// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://bqzdddsgmnshinckgtrq.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxemRkZHNnbW5zaGluY2tndHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyMTU2NDMsImV4cCI6MjA4OTc5MTY0M30.Y1WYj8h7EavKiJyHxkCAPk8BTd0eZuLTS8BbnmBi9lQ';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});